### ISSUE TITLE
Support output rotation

### ISSUE THREAD

**Issue by raybellis** [farsightsec/fstrm#16]
It would be very useful if `fstrm_capture` were able to rotate log files.

It would _probably_ be sufficient if on receipt of a given signal it closed the existing file (which may have been renamed by an external process) and re-started the original file.

**Comment by edmonds** [comment]
Hi, Ray:

Yes, it would, and it's been on my TODO list for a while. See #13 and #14 for previous discussion, and some code that's pending review.

**Comment by bapril** [comment]
Closing this issue as the code is merged.

**Comment by raybellis** [comment]
Where's the merge?   I see stuff in the 'next' branch but not in 'master' .  Thx.

**Comment by bapril** [comment]
Merged into next, we're working on a release now.
