### ISSUE TITLE
build fails on macOS due to clockid_t

### ISSUE THREAD

**Issue by ilovezfs** [farsightsec/fstrm#23]
Several errors that look like this:

```
./fstrm/fstrm-private.h:165:46: error: unknown type name 'clockid_t'; did you
      mean 'clock_t'?
bool fstrm__get_best_monotonic_clock_gettime(clockid_t *);
                                             ^~~~~~~~~
                                             clock_t
```

This can be fixed with the following patch (taken from https://github.com/RIOT-OS/RIOT/pull/2811/commits/e3a5bb25af96c45ce4eac2efbcd7e3c357f60e82):

```
diff --git a/fstrm/fstrm-private.h b/fstrm/fstrm-private.h
index f4d8991..185d110 100644
--- a/fstrm/fstrm-private.h
+++ b/fstrm/fstrm-private.h
@@ -31,6 +31,10 @@
 #include <string.h>
 #include <time.h>

+#if defined(__MACH__)
+typedef int clockid_t;
+#endif
+
 #include "fstrm.h"

 #include "libmy/my_alloc.h"
```

**Comment by edmonds** [comment]
Already handled in https://github.com/farsightsec/fstrm/commit/c5f091230ae74e7e28753dcecb7fc2006f0255b5.

**Comment by ilovezfs** [comment]
@edmonds any chance of getting a new tag?

**Comment by ilovezfs** [comment]
@edmonds tag would be for the sake of this: https://github.com/Homebrew/homebrew-core/pull/2291

**Comment by edmonds** [comment]
I'm no longer involved in release management for fstrm, but you might try pinging @bapril @vixie.

**Comment by ilovezfs** [comment]
@edmonds Ah, OK thanks!

**Comment by vixie** [comment]
checking into it. stand by.

**Comment by bapril** [comment]
Greetings,

I've tagged v0.3.0-rc1 on next. starting the review process now to get
it reviewed for release.

Thanks
Ben


On 6/24/16 8:13 PM, ilovezfs wrote:
> @edmonds <https://github.com/edmonds> tag would be for the sake of this:
> Homebrew/homebrew-core#2291
> <https://github.com/Homebrew/homebrew-core/pull/2291>
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/farsightsec/fstrm/issues/23#issuecomment-228494143>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAyhkJJE2aAq62CKNLnU6LQ1mQJXcp90ks5qPHKngaJpZM4I-NA8>.
> 

-- 
Ben April - Director of Engineering
Farsight Security, Inc.

**Comment by ilovezfs** [comment]
@vixie @bapril Thanks!
