### ISSUE TITLE
add debian infrastructure for .deb packaging

### ISSUE THREAD

**Issue by reedjc** [farsightsec/fstrm#31]
See example at https://anonscm.debian.org/cgit/users/edmonds/fstrm.git/

**Comment by edmonds** [comment]
Please don't, if you put Debian packaging in the upstream source it just makes a mess that I have to strip out.

**Comment by reedjc** [comment]
I need it for jessie and wheezy. Okay if I just do a debian branch that has ./debian/ directory? I have the same need for other FSI github projects -- some have debian directory and some don't. I understand Debiani has documented desire not to include debian/ directories.

**Comment by edmonds** [comment]
That's what I wanted to do originally. As long as the `debian` branch isn't used to build the release tarballs or the release tags, it's fine.

**Comment by reedjc** [comment]
I am using a debian branch for this.
