### ISSUE TITLE
fstrm_capture complain if using --port with --unix

### ISSUE THREAD

**Issue by reedjc** [farsightsec/fstrm#48]
fstrm_capture should warn or fail if using --port with --unix

**Comment by cmikk** [comment]
I would lean toward warn. An unused parameter should not cause the program to fail.

**Comment by reedjc** [comment]
By "unused parameter"  you mean because "-a" is not used?

**Comment by cmikk** [comment]
The opposite: the program has no use for the --port parameter, since the --unix parameter is a complete address. Thus, the program does not use --port.

**Comment by reedjc** [comment]
I understand. I don't see a problem with failing on an incompatible switch but I am fine with warning only.  I guess that same thought would be for setting --localtime or --gmtime without using -s.

**Comment by cmikk** [comment]
Interestingly, --localtime or --gmtime without --split still sends the filename through strftime(), so that the output file can be named after the startup time of the program. So, --split requires --{local,gm}time, but not vice versa.

I will correct the man page (in PR #43) to correct the logic.

**Comment by reedjc** [comment]
I merged to the upcoming release branch so closing this ticket (early). Thank you.
