### ISSUE TITLE
Installing on FreeBSD fails - or is it me?

### ISSUE THREAD

**Issue by leousr123** [farsightsec/fstrm#8]
I'm trying to install this on FreeBSD. I have automake, autoconf and libtool.
The command `./autogen.sh && ./configure && make && make check && make install` works untill `make`:

make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1880: Missing dependency operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1883: Need an operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1885: Need an operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1889: Missing dependency operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1890: warning: duplicate script for target "ifeq" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "ifeq" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1890: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "(no,yes)" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1891: warning: duplicate script for target "ifeq" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "ifeq" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1891: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "(no,yes)" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1892: warning: duplicate script for target "ifeq" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "ifeq" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1892: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "(no,yes)" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1893: warning: duplicate script for target "ifeq" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "ifeq" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1893: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "(no,yes)" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1894: warning: duplicate script for target "ifeq" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "ifeq" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1894: warning: duplicate script for target "(no,yes)" ignored
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1882: warning: using previous script for "(no,yes)" defined here
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1895: Need an operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1897: Need an operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1902: Missing dependency operator
make: "/usr/ports/distfiles/fstrm-0.2.0/Makefile" line 1908: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /usr/ports/distfiles/fstrm-0.2.0

So either I'm doing something wrong, or is there something else wrong.
So my question: how would I get this installed?

**Comment by edmonds** [comment]
Hi,

It looks like you're using BSD make. Can you try using GNU make? I think it's `gmake` on FreeBSD.

**Comment by leousr123** [comment]
Ha, great; that was an easy solution. Thanks.
(solved).

**Comment by leousr123** [comment]
I just submitted a port to simplify installation on FreeBSD
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=199292
