### ISSUE TITLE
fstrm_capture and outputing to stdout

### ISSUE THREAD

**Issue by adulau** [farsightsec/fstrm#9]
I have a small question regarding fstrm_capture and its use with dnstap. I was wondering why the default mode for fstrm_capture is to dump the output on a file and not to use stdout. 

To be able to do stuff like this:

~~~~
fstrm_capture  -t protobuf:dnstap.Dnstap -u /tmp/dnstap.sock -w - -ddddd | ..git/dnstap-ldns/dnstap-ldns -r -
~~~~

Is there a specific reason to not to do so? I was close to patch it but not sure if this is really a good idea.

Thanks a lot.

**Comment by edmonds** [comment]
Hi, Alexandre:

No real reason, just an oversight. If you have a patch please send it :-)

The only thing I'd insist on is to call `isatty(STDOUT_FILENO);` or similar and refuse to write to `stdout` if it's a terminal, since the Frame Streams output is binary.

**Comment by adulau** [comment]
Thank you Robert.  I'll do a patch.

**Comment by edmonds** [comment]
BTW, thanks for testing out dnstap! If you run into any issues feel free to also contact me directly (edmonds@fsi.io) if necessary or via the dnstap mailing list (http://lists.redbarn.org/mailman/listinfo/dnstap).

Also, if you're testing fstrm/dnstap with Unbound, I'm currently tracking down a crashing bug reported by a user, you may need to apply a patch (https://unbound.nlnetlabs.nl/pipermail/unbound-users/2015-April/003859.html).

**Comment by sjm42** [comment]
I accidentally did this here: https://github.com/farsightsec/fstrm/pull/15

**Comment by bapril** [comment]
Closing this , the code is merged into Next. working on a release now.
